### ISSUE TITLE
Windows 7 64bit is not supporting

### ISSUE THREAD

**Issue by kamesh-a** [Teamwork/node-afk#12]
Hello,

I was trying AFK Module in Windows 7 64bit, Following error throws up.
![idle_exe](https://cloud.githubusercontent.com/assets/3531949/5352333/02ddb8e0-7f8a-11e4-9542-87ae54d04235.png)

Please let me know, if any info needed to solve this issue.

**Comment by smithalan92** [comment]
I know this issue is 3.5 years old, but it should be fine with 1.0.0.
